# echo -n "-12:5" | python3 -m bnf exs/rational.bnf
<rac>  ::= <sign> <num> \: <nat>
<sign> ::= \+ | \- |
<nat>  ::= <dig> <nat> | <dig>
<num>  ::= <dig0> <num> | <dig0>
<dig>  ::= 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<dig0> ::= 0 | <dig>
